-- MySQL Script generated by MySQL Workbench
-- jue 25 oct 2018 16:35:01 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


--
-- Usuario con permisos completos
--

DROP USER IF EXISTS 'usertpjava'@'localhost';
CREATE USER 'usertpjava'@'localhost' IDENTIFIED BY 'usertpjava';
GRANT ALL PRIVILEGES ON * . * TO 'usertpjava'@'localhost';
FLUSH PRIVILEGES;

-- -----------------------------------------------------
-- Schema terminalTPJava
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `terminalTPJava` ;

-- -----------------------------------------------------
-- Schema terminalTPJava
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `terminalTPJava` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `terminalTPJava` ;

-- -----------------------------------------------------
-- Table `terminalTPJava`.`Servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `terminalTPJava`.`Servicio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `terminalTPJava`.`Servicio` (
  `idServicio` INT NOT NULL,
  `fechaServicio` DATE NULL,
  `horaServicio` VARCHAR(45) NULL,
  PRIMARY KEY (`idServicio`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `terminalTPJava`.`Destino`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `terminalTPJava`.`Destino` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `terminalTPJava`.`Destino` (
  `idDestino` INT NOT NULL,
  `localidad` VARCHAR(45) NULL,
  `porcentajeAumento` DOUBLE NULL,
  PRIMARY KEY (`idDestino`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `terminalTPJava`.`ServicioDestino`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `terminalTPJava`.`ServicioDestino` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `terminalTPJava`.`ServicioDestino` (
  `idServicio` INT NOT NULL,
  `idDestino` INT NOT NULL,
  `precio` DOUBLE NULL,
  PRIMARY KEY (`idServicio`, `idDestino`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `terminalTPJava`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `terminalTPJava`.`Persona` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `terminalTPJava`.`Persona` (
  `dni` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `tipoDni` VARCHAR(5) NULL,
  `fechaNac` DATE NULL,
  `fechaInicio` DATE NULL,
  `contacto` VARCHAR(45) NULL,
  `nombreUsuario` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `esAdmin` TINYINT(1) NOT NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `terminalTPJava`.`Micro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `terminalTPJava`.`Micro` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `terminalTPJava`.`Micro` (
  `patente` VARCHAR(45) NOT NULL,
  `porcentajeAumento` DOUBLE NULL,
  `marca` VARCHAR(45) NULL,
  `fechaUltimoControl` DATE NULL,
  PRIMARY KEY (`patente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `terminalTPJava`.`Butaca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `terminalTPJava`.`Butaca` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `terminalTPJava`.`Butaca` (
  `numButaca` INT NOT NULL,
  `patenteMicro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`numButaca`, `patenteMicro`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `terminalTPJava`.`MicroConductor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `terminalTPJava`.`MicroConductor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `terminalTPJava`.`MicroConductor` (
  `patente` VARCHAR(45) NOT NULL,
  `dniConductor` VARCHAR(45) NOT NULL,
  `idServicio` INT NOT NULL,
  PRIMARY KEY (`patente`, `dniConductor`, `idServicio`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `terminalTPJava`.`MicroServicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `terminalTPJava`.`MicroServicio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `terminalTPJava`.`MicroServicio` (
  `patente` VARCHAR(45) NOT NULL,
  `idServicio` INT NOT NULL,
  PRIMARY KEY (`patente`, `idServicio`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `terminalTPJava`.`PersonaServicioMicro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `terminalTPJava`.`PersonaServicioMicro` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `terminalTPJava`.`PersonaServicioMicro` (
  `dniPersona` VARCHAR(45) NOT NULL,
  `idServicio` INT NOT NULL,
  `patenteMicro` VARCHAR(45) NULL,
  `numButaca` INT NULL,
  PRIMARY KEY (`dniPersona`, `idServicio`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
