-- MySQL Script generated by MySQL Workbench
-- sáb 29 sep 2018 11:39:48 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema terminalTPJava
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `terminalTPJava` ;

-- -----------------------------------------------------
-- Schema terminalTPJava
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `terminalTPJava` DEFAULT CHARACTER SET utf8 ;
USE `terminalTPJava` ;

-- -----------------------------------------------------
-- Table `terminalTPJava`.`Servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `terminalTPJava`.`Servicio` ;

CREATE TABLE IF NOT EXISTS `terminalTPJava`.`Servicio` (
  `idServicio` INT NOT NULL,
  `fechaHoraServ` DATETIME NULL,
  PRIMARY KEY (`idServicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminalTPJava`.`Destino`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `terminalTPJava`.`Destino` ;

CREATE TABLE IF NOT EXISTS `terminalTPJava`.`Destino` (
  `idDestino` INT NOT NULL,
  `localidad` VARCHAR(45) NULL,
  `precio` DOUBLE NULL,
  `porcentajeAumento` DOUBLE NULL,
  PRIMARY KEY (`idDestino`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminalTPJava`.`ServicioDestino`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `terminalTPJava`.`ServicioDestino` ;

CREATE TABLE IF NOT EXISTS `terminalTPJava`.`ServicioDestino` (
  `idServicio` INT NOT NULL,
  `idDestino` INT NOT NULL,
  PRIMARY KEY (`idServicio`, `idDestino`),
  INDEX `fk_ServicioDestinoToDestino_idx` (`idDestino` ASC),
  CONSTRAINT `fk1_ServicioDestinoToServicio`
    FOREIGN KEY (`idServicio`)
    REFERENCES `terminalTPJava`.`Servicio` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ServicioDestinoToDestino`
    FOREIGN KEY (`idDestino`)
    REFERENCES `terminalTPJava`.`Destino` (`idDestino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminalTPJava`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `terminalTPJava`.`Persona` ;

CREATE TABLE IF NOT EXISTS `terminalTPJava`.`Persona` (
  `dni` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `tipoDni` VARCHAR(5) NULL,
  `fechaNac` DATE NULL,
  `fechaInicio` DATE NULL,
  `contacto` VARCHAR(45) NULL,
  `nombreUsuario` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminalTPJava`.`Butaca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `terminalTPJava`.`Butaca` ;

CREATE TABLE IF NOT EXISTS `terminalTPJava`.`Butaca` (
  `idButaca` INT NOT NULL,
  `dniUsuario` VARCHAR(45) NULL,
  PRIMARY KEY (`idButaca`),
  INDEX `fk1_ButacaToUsuario_idx` (`dniUsuario` ASC),
  CONSTRAINT `fk1_ButacaToUsuario`
    FOREIGN KEY (`dniUsuario`)
    REFERENCES `terminalTPJava`.`Persona` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminalTPJava`.`Micro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `terminalTPJava`.`Micro` ;

CREATE TABLE IF NOT EXISTS `terminalTPJava`.`Micro` (
  `patente` VARCHAR(45) NOT NULL,
  `dniConductor` VARCHAR(45) NULL,
  PRIMARY KEY (`patente`),
  INDEX `fk1_MicroToConductor_idx` (`dniConductor` ASC),
  CONSTRAINT `fk1_MicroToConductor`
    FOREIGN KEY (`dniConductor`)
    REFERENCES `terminalTPJava`.`Persona` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminalTPJava`.`MicroConductor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `terminalTPJava`.`MicroConductor` ;

CREATE TABLE IF NOT EXISTS `terminalTPJava`.`MicroConductor` (
  `patente` VARCHAR(45) NOT NULL,
  `dniConductor` VARCHAR(45) NOT NULL,
  `idServicio` INT NOT NULL,
  PRIMARY KEY (`patente`, `dniConductor`, `idServicio`),
  INDEX `fk1_MicroConductorToConductor_idx` (`dniConductor` ASC),
  INDEX `fk3_MicroConductorToServicio_idx` (`idServicio` ASC),
  CONSTRAINT `fk1_MicroConductorToConductor`
    FOREIGN KEY (`dniConductor`)
    REFERENCES `terminalTPJava`.`Persona` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk2_MicroConductorToMicro`
    FOREIGN KEY (`patente`)
    REFERENCES `terminalTPJava`.`Micro` (`patente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk3_MicroConductorToServicio`
    FOREIGN KEY (`idServicio`)
    REFERENCES `terminalTPJava`.`Servicio` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminalTPJava`.`MicroServicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `terminalTPJava`.`MicroServicio` ;

CREATE TABLE IF NOT EXISTS `terminalTPJava`.`MicroServicio` (
  `patente` INT NOT NULL,
  `idServicio` INT NOT NULL,
  `fechaServicio` DATETIME NOT NULL,
  PRIMARY KEY (`patente`, `idServicio`, `fechaServicio`),
  INDEX `fk2_MicroServicioToServicio_idx` (`idServicio` ASC),
  CONSTRAINT `fk1_MicroServicioToMicro`
    FOREIGN KEY (`patente`)
    REFERENCES `terminalTPJava`.`Micro` (`patente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk2_MicroServicioToServicio`
    FOREIGN KEY (`idServicio`)
    REFERENCES `terminalTPJava`.`Servicio` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminalTPJava`.`PersonaServicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `terminalTPJava`.`PersonaServicio` ;

CREATE TABLE IF NOT EXISTS `terminalTPJava`.`PersonaServicio` (
  `dniPersona` VARCHAR(45) NOT NULL,
  `idServicio` INT NOT NULL,
  PRIMARY KEY (`dniPersona`, `idServicio`),
  INDEX `fk2_PersonaServicioToServicio_idx` (`idServicio` ASC),
  CONSTRAINT `fk1_PersonaServicioToPersona`
    FOREIGN KEY (`dniPersona`)
    REFERENCES `terminalTPJava`.`Persona` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk2_PersonaServicioToServicio`
    FOREIGN KEY (`idServicio`)
    REFERENCES `terminalTPJava`.`Servicio` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
