-- MySQL Script generated by MySQL Workbench
-- sáb 20 oct 2018 10:31:35 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


--
-- Usuario con permisos completos
--

DROP USER IF EXISTS 'usertpjava'@'localhost';
CREATE USER 'usertpjava'@'localhost' IDENTIFIED BY 'usertpjava';
GRANT ALL PRIVILEGES ON * . * TO 'usertpjava'@'localhost';
FLUSH PRIVILEGES;


-- -----------------------------------------------------
-- Schema terminalTPJava
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `terminalTPJava` ;

-- -----------------------------------------------------
-- Schema terminalTPJava
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `terminalTPJava` DEFAULT CHARACTER SET utf8 ;
USE `terminalTPJava` ;

-- -----------------------------------------------------
-- Table `terminalTPJava`.`Servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `terminalTPJava`.`Servicio` ;

CREATE TABLE IF NOT EXISTS `terminalTPJava`.`Servicio` (
  `idServicio` INT NOT NULL,
  `fechaHoraServ` VARCHAR(45) NULL,
  PRIMARY KEY (`idServicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminalTPJava`.`Destino`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `terminalTPJava`.`Destino` ;

CREATE TABLE IF NOT EXISTS `terminalTPJava`.`Destino` (
  `idDestino` INT NOT NULL,
  `localidad` VARCHAR(45) NULL,
  `precio` DOUBLE NULL,
  `porcentajeAumento` DOUBLE NULL,
  PRIMARY KEY (`idDestino`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminalTPJava`.`ServicioDestino`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `terminalTPJava`.`ServicioDestino` ;

CREATE TABLE IF NOT EXISTS `terminalTPJava`.`ServicioDestino` (
  `idServicio` INT NOT NULL,
  `idDestino` INT NOT NULL,
  PRIMARY KEY (`idServicio`, `idDestino`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminalTPJava`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `terminalTPJava`.`Persona` ;

CREATE TABLE IF NOT EXISTS `terminalTPJava`.`Persona` (
  `dni` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `tipoDni` VARCHAR(5) NULL,
  `fechaNac` DATE NULL,
  `fechaInicio` VARCHAR(45) NULL,
  `contacto` VARCHAR(45) NULL,
  `nombreUsuario` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminalTPJava`.`Micro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `terminalTPJava`.`Micro` ;

CREATE TABLE IF NOT EXISTS `terminalTPJava`.`Micro` (
  `patente` VARCHAR(10) NOT NULL,
  `dniConductor` VARCHAR(45) NULL,
  `esCama` TINYINT(1) NOT NULL,
  PRIMARY KEY (`patente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminalTPJava`.`Butaca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `terminalTPJava`.`Butaca` ;

CREATE TABLE IF NOT EXISTS `terminalTPJava`.`Butaca` (
  `idButaca` INT NOT NULL,
  `dniUsuario` VARCHAR(45) NULL,
  `patenteMicro` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idButaca`, `patenteMicro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminalTPJava`.`MicroConductor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `terminalTPJava`.`MicroConductor` ;

CREATE TABLE IF NOT EXISTS `terminalTPJava`.`MicroConductor` (
  `patente` VARCHAR(10) NOT NULL,
  `dniConductor` VARCHAR(45) NOT NULL,
  `idServicio` INT NOT NULL,
  PRIMARY KEY (`patente`, `dniConductor`, `idServicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminalTPJava`.`MicroServicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `terminalTPJava`.`MicroServicio` ;

CREATE TABLE IF NOT EXISTS `terminalTPJava`.`MicroServicio` (
  `patente` VARCHAR(10) NOT NULL,
  `idServicio` INT NOT NULL,
  `fechaServicio` DATE NOT NULL,
  PRIMARY KEY (`patente`, `idServicio`, `fechaServicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `terminalTPJava`.`PersonaServicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `terminalTPJava`.`PersonaServicio` ;

CREATE TABLE IF NOT EXISTS `terminalTPJava`.`PersonaServicio` (
  `dniPersona` VARCHAR(45) NOT NULL,
  `idServicio` INT NOT NULL,
  PRIMARY KEY (`dniPersona`, `idServicio`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

